"""Sync models with schemas

Revision ID: 2f8afcaf6ee8
Revises: 001_initial
Create Date: 2026-02-12 21:39:21.322802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f8afcaf6ee8'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('subject', sa.String(length=100), nullable=True))
    op.drop_index('ix_conversations_student_id', table_name='conversations')
    op.add_column('learning_sessions', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('learning_sessions', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('learning_sessions', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('learning_sessions', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('learning_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_learning_sessions_student_id', table_name='learning_sessions')
    op.drop_column('learning_sessions', 'started_at')
    op.drop_column('learning_sessions', 'duration_seconds')
    op.drop_column('learning_sessions', 'ended_at')
    op.add_column('messages', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_index('ix_progress_records_student_id', table_name='progress_records')
    op.drop_index('ix_progress_records_topic_id', table_name='progress_records')
    op.add_column('quiz_attempts', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('graded_answers', sa.JSON(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('passed', sa.Boolean(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('time_exceeded', sa.Boolean(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('improvement_data', sa.JSON(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_quiz_attempts_student_id', table_name='quiz_attempts')
    op.add_column('quizzes', sa.Column('student_id', sa.String(length=36), nullable=True))
    op.add_column('quizzes', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('quizzes', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('max_score', sa.Integer(), nullable=True))
    op.drop_index('ix_quizzes_topic_id', table_name='quizzes')
    op.create_foreign_key(None, 'quizzes', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quizzes', 'total_points')
    op.drop_index('ix_subjects_grade', table_name='subjects')
    op.drop_index('ix_topics_subject_id', table_name='topics')
    op.drop_index('ix_weak_areas_student_id', table_name='weak_areas')
    op.add_column('worksheet_submissions', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('worksheet_submissions', sa.Column('graded_answers', sa.JSON(), nullable=True))
    op.add_column('worksheet_submissions', sa.Column('passed', sa.Boolean(), nullable=True))
    op.add_column('worksheet_submissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('worksheet_submissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('worksheet_submissions', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_worksheet_submissions_student_id', table_name='worksheet_submissions')
    op.add_column('worksheets', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('worksheets', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.add_column('worksheets', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('worksheets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_worksheets_student_id', table_name='worksheets')
    op.drop_column('worksheets', 'difficulty_level')
    op.drop_column('worksheets', 'total_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worksheets', sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('worksheets', sa.Column('difficulty_level', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), autoincrement=False, nullable=True))
    op.create_index('ix_worksheets_student_id', 'worksheets', ['student_id'], unique=False)
    op.drop_column('worksheets', 'updated_at')
    op.drop_column('worksheets', 'max_score')
    op.drop_column('worksheets', 'total_questions')
    op.drop_column('worksheets', 'difficulty')
    op.create_index('ix_worksheet_submissions_student_id', 'worksheet_submissions', ['student_id'], unique=False)
    op.alter_column('worksheet_submissions', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('worksheet_submissions', 'updated_at')
    op.drop_column('worksheet_submissions', 'created_at')
    op.drop_column('worksheet_submissions', 'passed')
    op.drop_column('worksheet_submissions', 'graded_answers')
    op.drop_column('worksheet_submissions', 'percentage')
    op.create_index('ix_weak_areas_student_id', 'weak_areas', ['student_id'], unique=False)
    op.create_index('ix_topics_subject_id', 'topics', ['subject_id'], unique=False)
    op.create_index('ix_subjects_grade', 'subjects', ['grade'], unique=False)
    op.add_column('quizzes', sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_index('ix_quizzes_topic_id', 'quizzes', ['topic_id'], unique=False)
    op.drop_column('quizzes', 'max_score')
    op.drop_column('quizzes', 'total_questions')
    op.drop_column('quizzes', 'difficulty')
    op.drop_column('quizzes', 'student_id')
    op.create_index('ix_quiz_attempts_student_id', 'quiz_attempts', ['student_id'], unique=False)
    op.drop_column('quiz_attempts', 'updated_at')
    op.drop_column('quiz_attempts', 'improvement_data')
    op.drop_column('quiz_attempts', 'time_exceeded')
    op.drop_column('quiz_attempts', 'passed')
    op.drop_column('quiz_attempts', 'graded_answers')
    op.drop_column('quiz_attempts', 'percentage')
    op.create_index('ix_progress_records_topic_id', 'progress_records', ['topic_id'], unique=False)
    op.create_index('ix_progress_records_student_id', 'progress_records', ['student_id'], unique=False)
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'extra_metadata')
    op.add_column('learning_sessions', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('learning_sessions', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('learning_sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index('ix_learning_sessions_student_id', 'learning_sessions', ['student_id'], unique=False)
    op.drop_column('learning_sessions', 'updated_at')
    op.drop_column('learning_sessions', 'completed')
    op.drop_column('learning_sessions', 'duration_minutes')
    op.drop_column('learning_sessions', 'end_time')
    op.drop_column('learning_sessions', 'start_time')
    op.create_index('ix_conversations_student_id', 'conversations', ['student_id'], unique=False)
    op.drop_column('conversations', 'subject')
    # ### end Alembic commands ###
